services:
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile
